pretrained: false
checkpoint: None
mode: train

model:
  model_name: qCIRIM
  use_reconstruction_module: false
  quantitative_module_recurrent_layer: GRU
  quantitative_module_conv_filters:
    - 64
    - 64
    - 4
  quantitative_module_conv_kernels:
    - 5
    - 3
    - 3
  quantitative_module_conv_dilations:
    - 1
    - 2
    - 1
  quantitative_module_conv_bias:
    - true
    - true
    - false
  quantitative_module_recurrent_filters:
    - 64
    - 64
    - 0
  quantitative_module_recurrent_kernels:
    - 1
    - 1
    - 0
  quantitative_module_recurrent_dilations:
    - 1
    - 1
    - 0
  quantitative_module_recurrent_bias:
    - true
    - true
    - false
  quantitative_module_depth: 2
  quantitative_module_time_steps: 8
  quantitative_module_conv_dim: 2
  quantitative_module_num_cascades: 1
  quantitative_module_no_dc: true
  quantitative_module_keep_eta: true
  quantitative_module_accumulate_estimates: true
  quantitative_module_signal_forward_model_sequence: MEGRE
  quantitative_module_dimensionality: 2
  quantitative_module_gamma_regularization_factors:
    - 150.0
    - 150.0
    - 1000.0
    - 150.0
  loss_fn: ssim
  loss_regularization_factors:
    - R2star: 3.0
    - S0: 1.0
    - B0: 1.0
    - phi: 1.0
#  loss_fn: mse or l1
#  loss_regularization_factors:
#    - R2star: 300.0
#    - S0: 500.0
#    - B0: 20000.0
#    - phi: 500.0
  shift_B0_input: false
  dimensionality: 2
  consecutive_slices: 1
  coil_combination_method: SENSE
  use_sens_net: false
  sens_chans: 8
  sens_pools: 4
  sens_mask_type: 2D
  fft_centered: false
  fft_normalization: backward
  spatial_dims:
    - -2
    - -1
  coil_dim: 2
  complex_data: true
  log_images: true

  train_ds:
    data_path: /data/projects/recon/data/qMRI/dimitris/data/Brain_MEGRE/multicoil_train
    sense_path: None
    mask_path: None
    initial_predictions_path: None
    challenge: multicoil
    batch_size: 1
    sample_rate: .1
    volume_sample_rate: None
    use_dataset_cache: false
    dataset_cache_file: None
    num_cols: None
    consecutive_slices: 1
    data_saved_per_slice: true
    complex_data: true
    apply_prewhitening: false
    apply_gcc: false
    coil_combination_method: SENSE
    dimensionality: 2
    sequence: MEGRE
    init_coil_dim: -1
    kspace_scaling_factor: 10000
    fft_centered: false
    fft_normalization: backward
    spatial_dims:
      - -2
      - -1
    coil_dim: 2
    precompute_quantitative_maps: false
    shift_B0_input: false
    TEs:
      - 3.0
      - 11.5
      - 20.0
      - 28.5
    mask_args:
      type: gaussian2d
      accelerations:
        - 3
      center_fractions:
        - 0.7
      scale: 0.02
      shift_mask: false
      use_seed: false
    normalize_inputs: true
    max_norm: true
    crop_size: None
    crop_before_masking: true
    kspace_zero_filling_size: None
    shuffle: true
    num_workers: 8
    drop_last: false
    pin_memory: false

  validation_ds:
    data_path: /data/projects/recon/data/qMRI/dimitris/data/Brain_MEGRE/multicoil_val
    sense_path: None
    mask_path: None
    initial_predictions_path: None
    challenge: multicoil
    batch_size: 1
    sample_rate: .1
    volume_sample_rate: None
    use_dataset_cache: false
    dataset_cache_file: None
    num_cols: None
    consecutive_slices: 1
    data_saved_per_slice: true
    complex_data: true
    apply_prewhitening: false
    apply_gcc: false
    coil_combination_method: SENSE
    dimensionality: 2
    sequence: MEGRE
    init_coil_dim: -1
    kspace_scaling_factor: 10000
    fft_centered: false
    fft_normalization: backward
    spatial_dims:
      - -2
      - -1
    coil_dim: 2
    precompute_quantitative_maps: false
    shift_B0_input: false
    TEs:
      - 3.0
      - 11.5
      - 20.0
      - 28.5
    mask_args:
      type: gaussian2d
      accelerations:
        - 3
      center_fractions:
        - 0.7
      scale: 0.02
      shift_mask: false
      use_seed: false
    normalize_inputs: true
    max_norm: true
    crop_size: None
    crop_before_masking: true
    kspace_zero_filling_size: None
    shuffle: false
    num_workers: 8
    drop_last: false
    pin_memory: false

  optim:
    name: adam
    lr: 0.001
    betas:
      - 0.9
      - 0.98
    weight_decay: 0.0
    sched:
      name: InverseSquareRootAnnealing
      min_lr: 0.0
      last_epoch: -1
      warmup_ratio: 0.1

trainer:
  strategy: ddp
  accelerator: gpu
  devices: 1
  num_nodes: 1
  max_epochs: 200
  precision: 16
  enable_checkpointing: false
  logger: false
  log_every_n_steps: 50
  check_val_every_n_epoch: -1
  max_steps: -1

exp_manager:
  exp_dir: /data/projects/recon/other/dkarkalousos/atommic/quantitative/trained_models/AHEAD_gaussian2d_12x/qRIM_mridc/
  create_tensorboard_logger: true
  create_wandb_logger: false
  wandb_logger_kwargs:
    project: ???
  files_to_copy: [ ]
